# Generated by Django 6.1.1 on 2026-09-27 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0003_colecao_produto_colecao_imagemproduto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='estoque',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='imagem',
        ),
    ]
